---

- hosts: all
  become: true
  tasks:

  - name: Update repo and Install apache2 and php packages
    package:
      update_cache: yes
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
