---

# Plays for all hosts
- hosts: all
  become: true
  tasks:

  - name: Install Updates (Ubuntu)
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install Updates (OracleLinux)
    dnf:
      update_cache: yes
    when: ansible_distribution == "OracleLinux"

# Plays for all hosts       
- hosts: all
  become: true
  roles:
    - base

# Plays for web servers
- hosts: web_servers
  become: true
  roles:
    - web_servers

# Plays to run file servers      
- hosts: file_servers
  become: true
  roles:
    - file_servers

# Plays for db servers
- hosts: db_servers
  become: true
  roles:
    - db_servers
